konstruktoid/hardening

- misc/audit.rules
- misc/logrotate.conf
- misc/sysctl.conf
- ubuntu.cfg
I added the config files referenced in the ubuntu.cfg from the ubuntu-config repo to this repo. This prevents me from having to sync two repos.
> Added config files to this repo

- scripts/23_disablemod
> mitigate Blueborne - CVE-2017-1000251

- scripts/18_sshdconfig
- tests/18_sshd.bats
> update sshd settings, moduli

- systemd.adoc
> replace google dns example

- misc/systemd_scan.sh
> add systemd .service scanner

- scripts/08_fstab
> WIP: home and /var/log perm test #32

- README.adoc
- scripts/22_auditd
- ubuntu.cfg
- ubuntu.sh
> add AUDITD_MODE variable, change default to 1

- README.adoc
- scripts/02_ufw
- scripts/18_sshdconfig
- tests/18_sshd.bats
- ubuntu.cfg
- ubuntu.sh
> SSH_PORT variable. Closes #46

- systemd.adoc
> update systemd examples

- scripts/24_aide
> #55 aide timer duplication

- misc/suid.list
> update suid list from @GTFOBins

- Vagrantfile
> use jammy/20220322

- .gitignore
- misc/genOSCAPreport.sh
- runTests.sh
> add OpenSCAP report script and make in run when testing

- Vagrantfile
> use jammy/20220414

- README.adoc
- scripts/disablefs
> dont disable vfat

- Vagrantfile
> add use ubuntu/jammy64 box

- runTests.sh
> run OSCAP early

- README.adoc
> update installation instructions

- misc/genOSCAPreport.sh
> update to OpeSCAP content version 0.1.61

- packer/aws.pkr.hcl
- packer/aws_configure.sh
> Add AWS Packer configuration

- README.adoc
- packer/aws_configure.sh
- scripts/packages
- ubuntu.cfg
- ubuntu.sh
- add `KEEP_SNAPD` variable
- ref #123 
> add KEEP_SNAPD variable

- README.adoc
> link to the Packer directory

- README.adoc
- scripts/sshdconfig
> place the sshd configuration in the `Include` directory if present

- misc/cowrie.list
- misc/passwords.list
> update password lists

- README.adoc
> format readme

- ubuntu.sh
> use resolv.conf if resolvectl isn't working

- scripts/pre
> quote EUID

- misc/genOSCAPreport.sh
> bump OSCAP Content to 0.1.63

- README.adoc
> add note regarding SLSA

- misc/cowrie.list
- misc/passwords.list
- misc/suid.list
> update password and suid lists

- misc/cowrie.list
- misc/passwords.list
> update password list

- misc/genOSCAPreport.sh
> update @OpenSCAP report script

- SECURITY.md
> add Github security policy

- .github/workflows/scorecards.yml
ref https://github.com/ossf/scorecard-action/issues/856
> update scorecard action

- misc/genOSCAPreport.sh
> update to OSCAP Content 0.1.64

- Vagrantfile
> use ubuntu/kinetic64

- README.adoc
> add note about idempotence

- misc/cowrie.list
> update honeypot password list

- misc/genOSCAPreport.sh
> refactor report generator

- .github/workflows/slsa.yml
> add REPOSITORY_NAME to GITHUB_ENV

- scripts/motdnews
> disable APT news

- README.adoc
- tests/motdnews.bats
> add test to verify that APT news is disabled, update readme

- Vagrantfile
> start testing Ubuntu 23.04 (Lunar Lobster)

- tests/sysctl.bats
> add /usr/lib/sysctl.* when verifying

- misc/audit.header
> report, dont ignore, errors

- misc/genOSCAPreport.sh
> update to OSCAP Content 0.1.66

- misc/genPasswordList.sh
- misc/passwords.list
> simplify genPasswordList.sh and update password lists

- Vagrantfile
> remove kinetic and add lunar daily from 20230202

- scripts/aptget
- tests/aptget.bats
> remove unused kernel packages

- scripts/timesyncd
- ubuntu.sh
Install `bind9-dnsutils`, `iputils-ping`, `net-tools` and `procps` if any required tools are missing.
Closes #282
> ensure dig and ping is installed

- scripts/aptget
> catch AllowRedirect

- README.adoc
- tests/runHostTestsCsv.sh
Add script: runHostTestsCsv.sh as an auxiliary output option that creates a csv report of the findings.
> Add script: runHostTestsCsv.sh as an auxiliary output option

- README.adoc
The error message was not clear while running the bash script to modified the documentation steps
> docs: modified documentation to make it more clear

- scripts/sshdconfig
Hi, I noticed an error in the sshd_config file settings
Here's fix
> sshdconfig AllowAgentForwarding fix

- scripts/sshdconfig
fixes https://github.com/konstruktoid/hardening/issues/536
> fix sshd.service could not be found

- misc/audit-base.rules
add audit rule for /var/lib/systemd/credential.secret, see https://www.freedesktop.org/software/systemd/man/latest/systemd-creds.html
> audit systemd credential.secret

- README.adoc
https://github.com/konstruktoid/hardening/issues/550
> clarify disablemod
